MONGO_USER_ID = 'abc'
MONGO_PASSWORD = 'Manish1999'
MONGO_DOMAIN = 'mongodb+srv://'
MONGO_TAIL_URL = '@cluster0.wjd9g.mongodb.net/?retryWrites=true&w=majority'
MYSQL_DOMAIN = 'localhost'
MYSQL_USERNAME = 'root'
MYSQL_PASSWORD = None
MYSQL_PORT = 3306
AWS_ACCESS_KEY = "AKIA2JL5BT4RR7V2I2NO"
AWS_SECRET_KEY = "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"